# Database configuration
db.driver=com.mysql.jdbc.Driver
# JDBC URL (example: jdbc:mysql://localhost:3306/acerosytrefilados?autoReconnect=true&useSSL=false)
db.url=jdbc:mysql://localhost:3306/acerosytrefilados?autoReconnect=true&useSSL=false
db.user=root
db.password=1234
